// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TvInteraction.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App int32

const (
	App_APP_OPEN      App = 0
	App_APP_UNINSTALL App = 1
)

var App_name = map[int32]string{
	0: "APP_OPEN",
	1: "APP_UNINSTALL",
}

var App_value = map[string]int32{
	"APP_OPEN":      0,
	"APP_UNINSTALL": 1,
}

func (x App) String() string {
	return proto.EnumName(App_name, int32(x))
}

func (App) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{0}
}

type Resp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{0}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

type Req struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{1}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

type KeycodeReq struct {
	Keycode              string   `protobuf:"bytes,1,opt,name=keycode,proto3" json:"keycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeycodeReq) Reset()         { *m = KeycodeReq{} }
func (m *KeycodeReq) String() string { return proto.CompactTextString(m) }
func (*KeycodeReq) ProtoMessage()    {}
func (*KeycodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{2}
}

func (m *KeycodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeycodeReq.Unmarshal(m, b)
}
func (m *KeycodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeycodeReq.Marshal(b, m, deterministic)
}
func (m *KeycodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeycodeReq.Merge(m, src)
}
func (m *KeycodeReq) XXX_Size() int {
	return xxx_messageInfo_KeycodeReq.Size(m)
}
func (m *KeycodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KeycodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_KeycodeReq proto.InternalMessageInfo

func (m *KeycodeReq) GetKeycode() string {
	if m != nil {
		return m.Keycode
	}
	return ""
}

type GetAllAppsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllAppsReq) Reset()         { *m = GetAllAppsReq{} }
func (m *GetAllAppsReq) String() string { return proto.CompactTextString(m) }
func (*GetAllAppsReq) ProtoMessage()    {}
func (*GetAllAppsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{3}
}

func (m *GetAllAppsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllAppsReq.Unmarshal(m, b)
}
func (m *GetAllAppsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllAppsReq.Marshal(b, m, deterministic)
}
func (m *GetAllAppsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllAppsReq.Merge(m, src)
}
func (m *GetAllAppsReq) XXX_Size() int {
	return xxx_messageInfo_GetAllAppsReq.Size(m)
}
func (m *GetAllAppsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllAppsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllAppsReq proto.InternalMessageInfo

type GetAllAppsResp struct {
	AppList              map[string]string `protobuf:"bytes,1,rep,name=app_list,json=appList,proto3" json:"app_list,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAllAppsResp) Reset()         { *m = GetAllAppsResp{} }
func (m *GetAllAppsResp) String() string { return proto.CompactTextString(m) }
func (*GetAllAppsResp) ProtoMessage()    {}
func (*GetAllAppsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{4}
}

func (m *GetAllAppsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllAppsResp.Unmarshal(m, b)
}
func (m *GetAllAppsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllAppsResp.Marshal(b, m, deterministic)
}
func (m *GetAllAppsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllAppsResp.Merge(m, src)
}
func (m *GetAllAppsResp) XXX_Size() int {
	return xxx_messageInfo_GetAllAppsResp.Size(m)
}
func (m *GetAllAppsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllAppsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllAppsResp proto.InternalMessageInfo

func (m *GetAllAppsResp) GetAppList() map[string]string {
	if m != nil {
		return m.AppList
	}
	return nil
}

type AppReq struct {
	App                  App      `protobuf:"varint,1,opt,name=app,proto3,enum=main.App" json:"app,omitempty"`
	Package              string   `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppReq) Reset()         { *m = AppReq{} }
func (m *AppReq) String() string { return proto.CompactTextString(m) }
func (*AppReq) ProtoMessage()    {}
func (*AppReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{5}
}

func (m *AppReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppReq.Unmarshal(m, b)
}
func (m *AppReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppReq.Marshal(b, m, deterministic)
}
func (m *AppReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppReq.Merge(m, src)
}
func (m *AppReq) XXX_Size() int {
	return xxx_messageInfo_AppReq.Size(m)
}
func (m *AppReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppReq proto.InternalMessageInfo

func (m *AppReq) GetApp() App {
	if m != nil {
		return m.App
	}
	return App_APP_OPEN
}

func (m *AppReq) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

type PlayReq struct {
	Package              string   `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	DeepLink             string   `protobuf:"bytes,2,opt,name=deepLink,proto3" json:"deepLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayReq) Reset()         { *m = PlayReq{} }
func (m *PlayReq) String() string { return proto.CompactTextString(m) }
func (*PlayReq) ProtoMessage()    {}
func (*PlayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{6}
}

func (m *PlayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayReq.Unmarshal(m, b)
}
func (m *PlayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayReq.Marshal(b, m, deterministic)
}
func (m *PlayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayReq.Merge(m, src)
}
func (m *PlayReq) XXX_Size() int {
	return xxx_messageInfo_PlayReq.Size(m)
}
func (m *PlayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PlayReq proto.InternalMessageInfo

func (m *PlayReq) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *PlayReq) GetDeepLink() string {
	if m != nil {
		return m.DeepLink
	}
	return ""
}

type TvSources struct {
	Tvsources            []string `protobuf:"bytes,1,rep,name=tvsources,proto3" json:"tvsources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TvSources) Reset()         { *m = TvSources{} }
func (m *TvSources) String() string { return proto.CompactTextString(m) }
func (*TvSources) ProtoMessage()    {}
func (*TvSources) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{7}
}

func (m *TvSources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TvSources.Unmarshal(m, b)
}
func (m *TvSources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TvSources.Marshal(b, m, deterministic)
}
func (m *TvSources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TvSources.Merge(m, src)
}
func (m *TvSources) XXX_Size() int {
	return xxx_messageInfo_TvSources.Size(m)
}
func (m *TvSources) XXX_DiscardUnknown() {
	xxx_messageInfo_TvSources.DiscardUnknown(m)
}

var xxx_messageInfo_TvSources proto.InternalMessageInfo

func (m *TvSources) GetTvsources() []string {
	if m != nil {
		return m.Tvsources
	}
	return nil
}

type TvActionReq struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TvActionReq) Reset()         { *m = TvActionReq{} }
func (m *TvActionReq) String() string { return proto.CompactTextString(m) }
func (*TvActionReq) ProtoMessage()    {}
func (*TvActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dee8e6591837ef9, []int{8}
}

func (m *TvActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TvActionReq.Unmarshal(m, b)
}
func (m *TvActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TvActionReq.Marshal(b, m, deterministic)
}
func (m *TvActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TvActionReq.Merge(m, src)
}
func (m *TvActionReq) XXX_Size() int {
	return xxx_messageInfo_TvActionReq.Size(m)
}
func (m *TvActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TvActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_TvActionReq proto.InternalMessageInfo

func (m *TvActionReq) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterEnum("main.App", App_name, App_value)
	proto.RegisterType((*Resp)(nil), "main.Resp")
	proto.RegisterType((*Req)(nil), "main.Req")
	proto.RegisterType((*KeycodeReq)(nil), "main.KeycodeReq")
	proto.RegisterType((*GetAllAppsReq)(nil), "main.GetAllAppsReq")
	proto.RegisterType((*GetAllAppsResp)(nil), "main.GetAllAppsResp")
	proto.RegisterMapType((map[string]string)(nil), "main.GetAllAppsResp.AppListEntry")
	proto.RegisterType((*AppReq)(nil), "main.AppReq")
	proto.RegisterType((*PlayReq)(nil), "main.PlayReq")
	proto.RegisterType((*TvSources)(nil), "main.TvSources")
	proto.RegisterType((*TvActionReq)(nil), "main.TvActionReq")
}

func init() {
	proto.RegisterFile("TvInteraction.proto", fileDescriptor_2dee8e6591837ef9)
}

var fileDescriptor_2dee8e6591837ef9 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xd1, 0x6a, 0xdb, 0x40,
	0x10, 0xac, 0xac, 0xc4, 0xb6, 0xc6, 0x76, 0xe2, 0x5c, 0x4c, 0x31, 0x6a, 0x1f, 0x52, 0x41, 0x82,
	0x53, 0xa8, 0x29, 0xee, 0x43, 0x4b, 0x28, 0x84, 0xa3, 0x84, 0x10, 0x6a, 0x1c, 0x23, 0xbb, 0xcf,
	0xe1, 0xaa, 0x5c, 0x8b, 0xb0, 0x2a, 0xad, 0xa5, 0x8b, 0xc0, 0xbf, 0xd0, 0x6f, 0xe9, 0x47, 0x96,
	0xd3, 0x49, 0x96, 0xdd, 0xe6, 0xed, 0x66, 0x67, 0x77, 0x47, 0x37, 0xa3, 0xc3, 0xe9, 0x32, 0xbf,
	0x8b, 0x95, 0x4c, 0x45, 0xa0, 0xc2, 0x24, 0x1e, 0x53, 0x9a, 0xa8, 0x84, 0x1d, 0xfc, 0x12, 0x61,
	0xec, 0x35, 0x71, 0xe0, 0xcb, 0x8c, 0xbc, 0x43, 0xd8, 0xbe, 0x5c, 0x7b, 0x17, 0xc0, 0x57, 0xb9,
	0x09, 0x92, 0x47, 0xe9, 0xcb, 0x35, 0x1b, 0xa2, 0xb5, 0x32, 0x68, 0x68, 0x9d, 0x59, 0x23, 0xc7,
	0xaf, 0xa0, 0x77, 0x8c, 0xde, 0xad, 0x54, 0x3c, 0x8a, 0x38, 0x51, 0xa6, 0x07, 0x7f, 0x5b, 0x38,
	0xda, 0xad, 0x64, 0xc4, 0x3e, 0xa3, 0x2d, 0x88, 0x1e, 0xa2, 0x30, 0x53, 0x43, 0xeb, 0xcc, 0x1e,
	0x75, 0x26, 0x6f, 0xc6, 0x5a, 0x73, 0xbc, 0xdf, 0x37, 0xe6, 0x44, 0xd3, 0x30, 0x53, 0x37, 0xb1,
	0x4a, 0x37, 0x7e, 0x4b, 0x18, 0xe4, 0x5e, 0xa1, 0xbb, 0x4b, 0xb0, 0x3e, 0xec, 0x95, 0xdc, 0x94,
	0xdf, 0xa1, 0x8f, 0x6c, 0x80, 0xc3, 0x5c, 0x44, 0x4f, 0x72, 0xd8, 0x28, 0x6a, 0x06, 0x5c, 0x35,
	0x3e, 0x59, 0xde, 0x35, 0x9a, 0x9c, 0x48, 0xdf, 0xe0, 0x15, 0x6c, 0x41, 0x54, 0x4c, 0x1d, 0x4d,
	0x1c, 0x23, 0xaf, 0x29, 0x5d, 0xd5, 0xd7, 0x23, 0x11, 0xac, 0xc4, 0xcf, 0x6a, 0x45, 0x05, 0xbd,
	0x6b, 0xb4, 0xe6, 0x91, 0xd8, 0x94, 0x1e, 0x54, 0x4d, 0xd6, 0x5e, 0x13, 0x73, 0xd1, 0x7e, 0x94,
	0x92, 0xa6, 0x61, 0xbc, 0x2a, 0xe7, 0xb7, 0xd8, 0xbb, 0x84, 0xb3, 0xcc, 0x17, 0xc9, 0x53, 0x1a,
	0xc8, 0x8c, 0xbd, 0x86, 0xa3, 0xf2, 0xcc, 0x80, 0xc2, 0x09, 0xc7, 0xaf, 0x0b, 0xde, 0x39, 0x3a,
	0xcb, 0x9c, 0x17, 0xc9, 0x68, 0xbd, 0x97, 0x68, 0x1a, 0xa6, 0x94, 0x2b, 0xd1, 0xdb, 0x0b, 0xd8,
	0x9c, 0x88, 0x75, 0xd1, 0xe6, 0xf3, 0xf9, 0xc3, 0xfd, 0xfc, 0x66, 0xd6, 0x7f, 0xc1, 0x4e, 0xd0,
	0xd3, 0xe8, 0xdb, 0xec, 0x6e, 0xb6, 0x58, 0xf2, 0xe9, 0xb4, 0x6f, 0x4d, 0xfe, 0x34, 0x30, 0xd8,
	0x8b, 0x7b, 0x21, 0xd3, 0x3c, 0x0c, 0x24, 0x7b, 0x87, 0x5e, 0x19, 0xad, 0x11, 0x63, 0x7d, 0x63,
	0x47, 0x9d, 0xb7, 0x0b, 0x53, 0x29, 0xd2, 0xfb, 0x08, 0xd4, 0x39, 0xb1, 0xd3, 0xff, 0x93, 0x5b,
	0xbb, 0x83, 0xe7, 0xe2, 0x64, 0xe7, 0x70, 0x38, 0x51, 0xa9, 0xd1, 0xad, 0x2d, 0xff, 0x67, 0xff,
	0x08, 0x1d, 0x6d, 0xf1, 0x97, 0x24, 0x56, 0x32, 0x56, 0xac, 0x67, 0xa8, 0xd2, 0xf5, 0xbd, 0xce,
	0xf7, 0x60, 0xb7, 0x52, 0xe9, 0x3f, 0xe1, 0xfe, 0x47, 0x6d, 0xaa, 0x53, 0x75, 0xac, 0xdd, 0x63,
	0x73, 0xac, 0xb9, 0x4b, 0xb4, 0x2b, 0x4b, 0xd9, 0x49, 0x45, 0x6e, 0x2d, 0xde, 0x5d, 0xfe, 0xbd,
	0x59, 0x3c, 0x86, 0x0f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x20, 0x61, 0x62, 0x00, 0x23, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TvInteractionServiceClient is the client API for TvInteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TvInteractionServiceClient interface {
	KeycodeAction(ctx context.Context, in *KeycodeReq, opts ...grpc.CallOption) (*Resp, error)
	GetAllApps(ctx context.Context, in *GetAllAppsReq, opts ...grpc.CallOption) (*GetAllAppsResp, error)
	AppAction(ctx context.Context, in *AppReq, opts ...grpc.CallOption) (*Resp, error)
	PlayContent(ctx context.Context, in *PlayReq, opts ...grpc.CallOption) (*Resp, error)
	GetListOfTvSources(ctx context.Context, in *Req, opts ...grpc.CallOption) (*TvSources, error)
	TvAction(ctx context.Context, in *TvActionReq, opts ...grpc.CallOption) (*Resp, error)
}

type tvInteractionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTvInteractionServiceClient(cc grpc.ClientConnInterface) TvInteractionServiceClient {
	return &tvInteractionServiceClient{cc}
}

func (c *tvInteractionServiceClient) KeycodeAction(ctx context.Context, in *KeycodeReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/main.TvInteractionService/KeycodeAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvInteractionServiceClient) GetAllApps(ctx context.Context, in *GetAllAppsReq, opts ...grpc.CallOption) (*GetAllAppsResp, error) {
	out := new(GetAllAppsResp)
	err := c.cc.Invoke(ctx, "/main.TvInteractionService/GetAllApps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvInteractionServiceClient) AppAction(ctx context.Context, in *AppReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/main.TvInteractionService/AppAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvInteractionServiceClient) PlayContent(ctx context.Context, in *PlayReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/main.TvInteractionService/PlayContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvInteractionServiceClient) GetListOfTvSources(ctx context.Context, in *Req, opts ...grpc.CallOption) (*TvSources, error) {
	out := new(TvSources)
	err := c.cc.Invoke(ctx, "/main.TvInteractionService/GetListOfTvSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tvInteractionServiceClient) TvAction(ctx context.Context, in *TvActionReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/main.TvInteractionService/TvAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TvInteractionServiceServer is the server API for TvInteractionService service.
type TvInteractionServiceServer interface {
	KeycodeAction(context.Context, *KeycodeReq) (*Resp, error)
	GetAllApps(context.Context, *GetAllAppsReq) (*GetAllAppsResp, error)
	AppAction(context.Context, *AppReq) (*Resp, error)
	PlayContent(context.Context, *PlayReq) (*Resp, error)
	GetListOfTvSources(context.Context, *Req) (*TvSources, error)
	TvAction(context.Context, *TvActionReq) (*Resp, error)
}

// UnimplementedTvInteractionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTvInteractionServiceServer struct {
}

func (*UnimplementedTvInteractionServiceServer) KeycodeAction(ctx context.Context, req *KeycodeReq) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeycodeAction not implemented")
}
func (*UnimplementedTvInteractionServiceServer) GetAllApps(ctx context.Context, req *GetAllAppsReq) (*GetAllAppsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllApps not implemented")
}
func (*UnimplementedTvInteractionServiceServer) AppAction(ctx context.Context, req *AppReq) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppAction not implemented")
}
func (*UnimplementedTvInteractionServiceServer) PlayContent(ctx context.Context, req *PlayReq) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayContent not implemented")
}
func (*UnimplementedTvInteractionServiceServer) GetListOfTvSources(ctx context.Context, req *Req) (*TvSources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListOfTvSources not implemented")
}
func (*UnimplementedTvInteractionServiceServer) TvAction(ctx context.Context, req *TvActionReq) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TvAction not implemented")
}

func RegisterTvInteractionServiceServer(s *grpc.Server, srv TvInteractionServiceServer) {
	s.RegisterService(&_TvInteractionService_serviceDesc, srv)
}

func _TvInteractionService_KeycodeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeycodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvInteractionServiceServer).KeycodeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TvInteractionService/KeycodeAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvInteractionServiceServer).KeycodeAction(ctx, req.(*KeycodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvInteractionService_GetAllApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAppsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvInteractionServiceServer).GetAllApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TvInteractionService/GetAllApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvInteractionServiceServer).GetAllApps(ctx, req.(*GetAllAppsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvInteractionService_AppAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvInteractionServiceServer).AppAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TvInteractionService/AppAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvInteractionServiceServer).AppAction(ctx, req.(*AppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvInteractionService_PlayContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvInteractionServiceServer).PlayContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TvInteractionService/PlayContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvInteractionServiceServer).PlayContent(ctx, req.(*PlayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvInteractionService_GetListOfTvSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvInteractionServiceServer).GetListOfTvSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TvInteractionService/GetListOfTvSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvInteractionServiceServer).GetListOfTvSources(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _TvInteractionService_TvAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TvActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TvInteractionServiceServer).TvAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.TvInteractionService/TvAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TvInteractionServiceServer).TvAction(ctx, req.(*TvActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TvInteractionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.TvInteractionService",
	HandlerType: (*TvInteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeycodeAction",
			Handler:    _TvInteractionService_KeycodeAction_Handler,
		},
		{
			MethodName: "GetAllApps",
			Handler:    _TvInteractionService_GetAllApps_Handler,
		},
		{
			MethodName: "AppAction",
			Handler:    _TvInteractionService_AppAction_Handler,
		},
		{
			MethodName: "PlayContent",
			Handler:    _TvInteractionService_PlayContent_Handler,
		},
		{
			MethodName: "GetListOfTvSources",
			Handler:    _TvInteractionService_GetListOfTvSources_Handler,
		},
		{
			MethodName: "TvAction",
			Handler:    _TvInteractionService_TvAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TvInteraction.proto",
}
